var liste_clients = {
	"total" : "23",
	"results" : [{
			"id_commande" : "4",
			"nom_client" : "TIA MARC",
			"tel_client" : "57 39 93 85",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "JAUGE",
			"marque_voiture" : "TOYOTA",
			"modele_voiture" : "TOYOTA1",
			"annee_voiture" : "2005",
			"date_livraison_prevue" : "2016-04-14",
			"date_livraison_effect" : "2016-04-29",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "5",
			"nom_client" : "TIA MARC",
			"tel_client" : "57 39 93 85",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "JAUGE",
			"marque_voiture" : "TOYOTA",
			"modele_voiture" : "TOYOTA1",
			"annee_voiture" : "2005",
			"date_livraison_prevue" : "2016-04-14",
			"date_livraison_effect" : "2016-04-29",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "11",
			"nom_client" : "tia gue",
			"tel_client" : "marc",
			"produit1" : "",
			"produit2" : "",
			"produit3" : "",
			"produit4" : "",
			"marque_voiture" : "",
			"modele_voiture" : "",
			"annee_voiture" : "0",
			"date_livraison_prevue" : "0000-00-00",
			"date_livraison_effect" : "0000-00-00",
			"situation_commande" : ""
		}, {
			"id_commande" : "12",
			"nom_client" : "tia gue",
			"tel_client" : "le grand",
			"produit1" : "",
			"produit2" : "",
			"produit3" : "",
			"produit4" : "",
			"marque_voiture" : "",
			"modele_voiture" : "",
			"annee_voiture" : "0",
			"date_livraison_prevue" : "0000-00-00",
			"date_livraison_effect" : "0000-00-00",
			"situation_commande" : ""
		}, {
			"id_commande" : "13",
			"nom_client" : "TOURE ALI",
			"tel_client" : "MECANICIEN AUTO",
			"produit1" : "",
			"produit2" : "",
			"produit3" : "",
			"produit4" : "",
			"marque_voiture" : "",
			"modele_voiture" : "",
			"annee_voiture" : "0",
			"date_livraison_prevue" : "0000-00-00",
			"date_livraison_effect" : "0000-00-00",
			"situation_commande" : ""
		}, {
			"id_commande" : "15",
			"nom_client" : "tia",
			"tel_client" : "75857569",
			"produit1" : "on",
			"produit2" : "on",
			"produit3" : "on",
			"produit4" : "on",
			"marque_voiture" : "mimi",
			"modele_voiture" : "momo",
			"annee_voiture" : "1252",
			"date_livraison_prevue" : "2016-04-14",
			"date_livraison_effect" : "2016-04-30",
			"situation_commande" : ""
		}, {
			"id_commande" : "16",
			"nom_client" : "koffi",
			"tel_client" : "78 58 96 25",
			"produit1" : "off",
			"produit2" : "off",
			"produit3" : "off",
			"produit4" : "on",
			"marque_voiture" : "tata",
			"modele_voiture" : "titi",
			"annee_voiture" : "2015",
			"date_livraison_prevue" : "2016-04-15",
			"date_livraison_effect" : "2016-04-09",
			"situation_commande" : ""
		}, {
			"id_commande" : "17",
			"nom_client" : "koffi",
			"tel_client" : "78 58 96 25",
			"produit1" : "off",
			"produit2" : "off",
			"produit3" : "off",
			"produit4" : "on",
			"marque_voiture" : "tata",
			"modele_voiture" : "titi",
			"annee_voiture" : "2015",
			"date_livraison_prevue" : "2016-04-15",
			"date_livraison_effect" : "2016-04-09",
			"situation_commande" : ""
		}, {
			"id_commande" : "18",
			"nom_client" : "marc",
			"tel_client" : "58 58 66 25",
			"produit1" : "off",
			"produit2" : "off",
			"produit3" : "off",
			"produit4" : "off",
			"marque_voiture" : "dodo",
			"modele_voiture" : "dadada",
			"annee_voiture" : "2011",
			"date_livraison_prevue" : "2016-04-15",
			"date_livraison_effect" : "2016-04-21",
			"situation_commande" : ""
		}, {
			"id_commande" : "19",
			"nom_client" : "asoumou",
			"tel_client" : "96 58 32 85",
			"produit1" : "on",
			"produit2" : "off",
			"produit3" : "on",
			"produit4" : "off",
			"marque_voiture" : "anta",
			"modele_voiture" : "ototo",
			"annee_voiture" : "2000",
			"date_livraison_prevue" : "2016-04-04",
			"date_livraison_effect" : "2016-04-13",
			"situation_commande" : ""
		}, {
			"id_commande" : "20",
			"nom_client" : "h",
			"tel_client" : "h",
			"produit1" : "on",
			"produit2" : "on",
			"produit3" : "on",
			"produit4" : "on",
			"marque_voiture" : "h",
			"modele_voiture" : "h",
			"annee_voiture" : "0",
			"date_livraison_prevue" : "2016-04-08",
			"date_livraison_effect" : "2016-04-08",
			"situation_commande" : ""
		}, {
			"id_commande" : "21",
			"nom_client" : "ggttf",
			"tel_client" : "fffgghg",
			"produit1" : "CAMERA",
			"produit2" : "on",
			"produit3" : "off",
			"produit4" : "off",
			"marque_voiture" : "ytyty",
			"modele_voiture" : "hhjuy",
			"annee_voiture" : "0",
			"date_livraison_prevue" : "2016-04-07",
			"date_livraison_effect" : "2016-04-23",
			"situation_commande" : ""
		}, {
			"id_commande" : "22",
			"nom_client" : "TETE",
			"tel_client" : "57 65 85 32",
			"produit1" : "CAMERA",
			"produit2" : "RIEN",
			"produit3" : "RADIO-DVD",
			"produit4" : "RIEN",
			"marque_voiture" : "JAJA",
			"modele_voiture" : "KIKA",
			"annee_voiture" : "2536",
			"date_livraison_prevue" : "2016-04-01",
			"date_livraison_effect" : "2016-03-26",
			"situation_commande" : ""
		}, {
			"id_commande" : "23",
			"nom_client" : "allana",
			"tel_client" : "68 95 32 98",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "NON LIVREE",
			"marque_voiture" : "haha",
			"modele_voiture" : "ohoho",
			"annee_voiture" : "3232",
			"date_livraison_prevue" : "2016-04-08",
			"date_livraison_effect" : "2016-04-20",
			"situation_commande" : ""
		}, {
			"id_commande" : "24",
			"nom_client" : "allana",
			"tel_client" : "68 95 32 98",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "RIEN",
			"marque_voiture" : "haha",
			"modele_voiture" : "ohoho",
			"annee_voiture" : "3232",
			"date_livraison_prevue" : "2016-04-08",
			"date_livraison_effect" : "2016-04-20",
			"situation_commande" : ""
		}, {
			"id_commande" : "25",
			"nom_client" : "affa",
			"tel_client" : "56\/65\/98\/32",
			"produit1" : "TRAQUEUR",
			"produit2" : "RADIO-DVD",
			"produit3" : "JAUGE",
			"produit4" : "LIVREE",
			"marque_voiture" : "nene",
			"modele_voiture" : "xaxa",
			"annee_voiture" : "5241",
			"date_livraison_prevue" : "2016-04-05",
			"date_livraison_effect" : "0000-00-00",
			"situation_commande" : "2016-04-20"
		}, {
			"id_commande" : "26",
			"nom_client" : "koko",
			"tel_client" : "56\/65\/98\/32",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RIEN",
			"produit4" : "JAUGE",
			"marque_voiture" : "nenemamaa",
			"modele_voiture" : "xaxalala",
			"annee_voiture" : "5241",
			"date_livraison_prevue" : "2016-04-15",
			"date_livraison_effect" : "2016-04-27",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "27",
			"nom_client" : "koffi koffi",
			"tel_client" : "51 35 64 32",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "RIEN",
			"marque_voiture" : "tree",
			"modele_voiture" : "dede",
			"annee_voiture" : "1212",
			"date_livraison_prevue" : "2016-05-04",
			"date_livraison_effect" : "2016-05-19",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "28",
			"nom_client" : "kacou ali",
			"tel_client" : "57 55 87 58",
			"produit1" : "CAMERA",
			"produit2" : "RIEN",
			"produit3" : "RADIO-DVD",
			"produit4" : "RIEN",
			"marque_voiture" : "fefre",
			"modele_voiture" : "sesa",
			"annee_voiture" : "1212",
			"date_livraison_prevue" : "2016-05-18",
			"date_livraison_effect" : "2016-05-27",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "29",
			"nom_client" : "AYA",
			"tel_client" : "85 87 58 62",
			"produit1" : "CAMERA",
			"produit2" : "RIEN",
			"produit3" : "RADIO-DVD",
			"produit4" : "JAUGE",
			"marque_voiture" : "NONO",
			"modele_voiture" : "TUTU",
			"annee_voiture" : "1452",
			"date_livraison_prevue" : "2016-05-11",
			"date_livraison_effect" : "2016-05-26",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "30",
			"nom_client" : "malik",
			"tel_client" : "58 52 64 32",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RIEN",
			"produit4" : "JAUGE",
			"marque_voiture" : "cece",
			"modele_voiture" : "saza",
			"annee_voiture" : "1452",
			"date_livraison_prevue" : "2016-05-12",
			"date_livraison_effect" : "2016-05-20",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "31",
			"nom_client" : "kaka",
			"tel_client" : "87 65 98 12",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "RIEN",
			"marque_voiture" : "koko",
			"modele_voiture" : "haha",
			"annee_voiture" : "5214",
			"date_livraison_prevue" : "2016-05-10",
			"date_livraison_effect" : "2016-05-24",
			"situation_commande" : "LIVREE"
		}, {
			"id_commande" : "32",
			"nom_client" : "tato",
			"tel_client" : "87 65 98 12",
			"produit1" : "CAMERA",
			"produit2" : "TRAQUEUR",
			"produit3" : "RADIO-DVD",
			"produit4" : "RIEN",
			"marque_voiture" : "jaja",
			"modele_voiture" : "papo",
			"annee_voiture" : "5214",
			"date_livraison_prevue" : "2016-05-10",
			"date_livraison_effect" : "2016-05-24",
			"situation_commande" : "LIVREE"
		}
	]
}
